### ISSUE TITLE
Run error on loader.js (Cannot find module 'worker_threads')

### ISSUE THREAD

**Issue by agap2-ag** [jlooper/olympic-app#1]
I was really looking forward to run this app while Jen was presenting in MS Build, but after `npm install`, doing `npm run dev` keeps giving me:

    > vite

    internal/modules/cjs/loader.js:638
        throw err;
        ^

    Error: Cannot find module 'worker_threads'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
        at Function.Module._load (internal/modules/cjs/loader.js:562:25)
        at Module.require (internal/modules/cjs/loader.js:690:17)
        at require (internal/modules/cjs/helpers.js:25:18)
        at Object.<anonymous> (\PATH\olympic-app\node_modules\vite\dist\node\chunks\dep-e9a16784.js:22:20)
        at Module._compile (internal/modules/cjs/loader.js:776:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)

This happens in both _student_ and _main_ branches at this time and the install had no visible issues.

**Comment by jlooper** [comment]
hi! how did you install vite? Let me dig!

**Comment by jlooper** [comment]
https://github.com/vitejs/vite/issues/1700 - looks like your node version might be old, it needs to be 12+

**Comment by agap2-ag** [comment]
I am ashamed to write that I was using v10 of node 😅
I installed the LTS from: https://nodejs.org/en/download
And directly run `npm run dev` again: it ran perfectly on localhost:3000 after that!

Thank you for the help, resources and awesome presentation @jlooper 😉👍
